name: Publish Fig Spec

on:
    push:
        branches:
            - 'release'
jobs:
    push-to-fig:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  check-latest: true
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install

            - name: Output Fig Spec
              run: pnpm fig > spec.ts

            - name: Publish Fig Spec
              run: npx @fig/publish-spec --spec-path ./spec.ts
